." Manpage for libqainternal.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "libqainternal man page"
.SH NAME
libqainternal
.SH SYNOPSIS
See https://wiki.innerweb.novell.com/index.php/RD-OPS_QA/InternalAPI
.SH TYPE
lib
.SH DESCRIPTION
Internal QA API used in tests. Shell and C binding. 
.br
See https://wiki.innerweb.novell.com/index.php/RD-OPS_QA/InternalAPI for details.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
The functions provided by the library can be used in various QA tests.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Perl binding is no longer supported. This package is obsolete.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Mix of our code and GPL v2 or later code. Not sure if it has ever been distributed externally or not, but I suspect it has.
.SH LICENSE
SUSE Proprietary (although may end up all being GPL v2 or later, depending on outcome of legal review).
.SH UPSTREAM
None.
.SH AUTHOR
Frank Seidel <fseidel@suse.de>, Martin Mrazik
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>
