." Manpage for qa_sdk_spec_generator.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_sdk_spec_generator man page"
.SH NAME
qa_sdk_spec_generator
.SH SYNOPSIS
qa_sdk_spec_generator <package_name> [option]
.SH TYPE
test tools
.SH DESCRIPTION
generate a sample of spec file
.SH README
None.
.SH OPTIONS
-a author name
.br
-e email address
.br
-l one_line "changelog"
.br
-v version
.SH WHAT IT DOES
A new spec file will be generated in the current directory.
.SH COMMON PROBLEMS
None
.SH WARNINGS
None
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. Not to be redistributed.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
Jerry Tang  <jtang@novell.com>
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
