<?php
/* ****************************************************************************
  Copyright (c) 2013 Unpublished Work of SUSE. All Rights Reserved.
  
  THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
  CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
  RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
  THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
  THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
  TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
  PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
  PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
  AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
  LIABILITY.
  
  SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
  WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
  AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
  LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
  WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
  ****************************************************************************
 */

    /**
     * Contents of the <tt>autopxe</tt> page  
     */
    if (!defined('HAMSTA_FRONTEND')) {
        $go = 'autopxe';
        return require("index.php");
    }
?>

<form id="autopxe" name="autopxe" method="post" action="index.php?go=autopxe" onsubmit="return checkcontents(this)">
  <p>
    This page allows you to install a machine with AutoPXE. It can be
    used in cases of a broken installation or install a raw server or
    machine without the "hamsta-client".
  </p>

  <h3>Installation repository</h3>
  <p>
    <label for="repo_products">Product:</label> <select name="repo_products" id="repo_products"></select>
    <label for="repo_archs">Arch:</label> <select name="repo_archs" id="repo_archs"></select>
    <br />

    <label for="repourl" class="text-main">Repository URL:</label>
    <input type="text" name="repourl" id="repourl" size="66"
	   value="<?php if(isset($_POST["repourl"])){echo $_POST["repourl"];} ?>"
	   title="The installation URL"
	   placeholder="Put your installation URL here or select from options"
	   required/>
  </p>

  <h3>Machine identification</h3>
  <p>
    <span class="text-main">
      You can define a machine to install using options below. Using
      MAC address is preferred. A raw server can be only served by MAC
      address.
    </span>
  </p>

  <label for="type" class="text-main">Type:</label>
  <select name="type" id="type">
    <option value="ip">IP Address</option>
    <option value="mac" selected="selected">MAC Address</option>
  </select>

  <label for="address" class="text-main">Address:</label>
  <input type="text" name="address" id="address"
	 title="The type is selected in the drop-down menu."
	 placeholder="Fill in address"
	 required/>
  <br />
  <br />

  <h3>Other options</h3>
  <input type="checkbox" name="hamsta" id="hamsta"/>
  <label for="hamsta" class="text-main">Install Hamsta</label>
  <br />

  <input type="checkbox" name="loopback" id="loopback"/>
  <label for="loopback" class="text-main">Assign hostname to loopback IP</label>

  <p>
    <span class="text-main">
      <B>NOTE</B> that temporary PXE files generated by this function
      will be deleted in 20 minutes automatically. You may run this
      function again after they expire.
    </span>
  </p>

  <input type="submit" name="submit" value="submit" id="submit" />
<?php
print_install_post_data ();
?>
</form>

<script src="js/install_product.js"></script>
