<?php
/* ****************************************************************************
  Copyright © 2011 Unpublished Work of SUSE. All Rights Reserved.
  
  THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
  CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
  RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
  THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
  THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
  TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
  PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
  PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
  AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
  LIABILITY.
  
  SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
  WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
  AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
  LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
  WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
  ****************************************************************************
 */

    /**
     * Contents of the <tt>send_job</tt> page  
     */
    if (!defined('HAMSTA_FRONTEND')) {
        $go = 'autopxe';
        return require("index.php");
    }
?>
<h5 class="text-small text-blue">You are about to install a machine with AutoPXE.<br /></h5>
<form id="autopxe" name="autopxe" method="post" action="index.php?go=autopxe" onsubmit="return checkcontents(this)">
  <label for="textfield" class="text-main">This page allows you to install a broken installation, or a raw server. In other words, install a server without using the "hamsta-client".<br />
  <br />
  Install repo:</label>
<label for="repo_products">Product:</label><select name="repo_products" id="repo_products"></select>
<label for="repo_archs">Arch:</label> <select name="repo_archs" id="repo_archs"></select>
<input type="text" name="repourl" id="repourl" size="66" value="<?php if(isset($_POST["repourl"])){echo $_POST["repourl"];} ?>" title="required: url"/><span class="required">*</span><span class="text-main"></span>
  <br />
  <br />
  <span class="text-main">You can initiate the installation via MAC or IP address. Just select the method you want to use and then type in the MAC or IP of the machine you want to install. Note: MAC address is preferred. A raw server can be only served by MAC address.</span><br /><br />
  <label for="select" class="text-main">Type:</label>
  <select name="type" id="type">
    <option value="ip">IP Address</option>
    <option value="mac" selected="selected">MAC Address</option>
  </select>
  &nbsp; &nbsp;
  <label for="label" class="text-main">Address:</label>
  <input type="text" name="address" id="address" title="required: address"/></textarea><span class="required">*</span>
  <br />
  <br />
  <label for="label" class="text-main">Need Hamsta?</label>
  <label class="text-main"><input type="checkbox" name="hamsta" id="hamsta"/>Yes!</label>
  <br />
  <br />
  <span class="text-main"><B>BE NOTICED:</B> temporary pxe files generated by this function will be deleted in 5 minutes automatically. So you may re-run this function after they expired. </span><br /><br />
  <label for="submit"></label>
  <input type="submit" name="submit" value="submit" id="submit" /> &nbsp;
  <br />
</form>

<script>
var old_repo_product = "";
var old_repo_arch = "";

// Iterate $data and insert all options to select box $id
var insert_options = function (id, data, old_selected){
        $(id).empty();
        $.each(data, function(i, item){
                $(id).append('<option value="' + item + '">' + item + '</option>');
        });//each
        $(id).val(old_selected);
        $(id).change();
}

var get_repo_archs = function() {
        old_repo_product =  $("#repo_products option:selected").text();
        var para= { product: $("#repo_products option:selected").text()};
        $.getJSON("html/search_repo.php", para, function(data){
                insert_options("#repo_archs", data, old_repo_arch);
        });
        return false;
};

var get_repo_urls = function (){
        old_repo_arch =  $("#repo_archs option:selected").text();
        var para= { product: $("#repo_products option:selected").text(), 
                arch: $("#repo_archs option:selected").text()};
        $.getJSON("html/search_repo.php", para, function(data){
        $("#repourl").attr("value", data[0]);
        });
        return false;
};

$("#repo_products").change(get_repo_archs);
$("#repo_archs").change(get_repo_urls);

$(document).ready(function(){
        // Setup ajax messaging
        $('#message')
            .ajaxStart(function() {
              $(this).text("Loading...");
            }).ajaxStop(function() {
              $(this).empty();
            });
        // Reinstall with updates options
        $('#startupdate')
                .change(function() {
                        var updateVal = $('#startupdate').val();
                        if(updateVal == 'update-smt')
                        {
                                $('#updateoptions-smt').slideDown();
                                $('#updateoptions-reg').hide();
                        }
                        else if(updateVal == 'update-reg')
                        {
                                $('#updateoptions-smt').hide();
                                $('#updateoptions-reg').slideDown();
                        }
                        else
                        {
                                $('#updateoptions-smt').hide();
                                $('#updateoptions-reg').hide();
                        }
                });

        // For dropdown lists, load products
        $.getJSON("html/search_repo.php", function(data){
                insert_options("#repo_products", data, old_repo_product);
        });
});
</script>
