." Manpage for qa_lib_virtauto.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_lib_virtauto man page"
.SH NAME
qa_lib_virtauto
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
QA library for virtualization automation.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later. Developed for internal use; contains internal code, ips, install sources, etc.
.SH UPSTREAM
None.
.SH AUTHOR
Dan Collingridge <dcollingridge@novell.com>, Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>
