ALTER TABLE arch CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config_module CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `group` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE group_machine CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE job CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE job_on_machine CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE job_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE machine CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE machine_status CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE module CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE module_part CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE module_name CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE product CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `release` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE hamsta_db DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE module_part ADD INDEX(element);
