INSERT INTO privilege (privilege, descr) VALUES ('machine_powerswitch_reserved', 'Use powerswitch of machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_delete_reserved', 'Delete a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_reinstall_reserved', 'Reinstall a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_edit_reserved', 'Edit a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_free_reserved', 'Free a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_send_job_reserved', 'Send job to a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_vnc_reserved', 'Open VNC terminal to a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_terminal_reserved', 'Open terminal to a machine reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_merge_reserved', 'Merge a machines reserved by other user');
INSERT INTO privilege (privilege, descr) VALUES ('machine_add_to_group_reserved', 'Add a machines reserved by other user into a group');
INSERT INTO privilege (privilege, descr) VALUES ('machine_remove_from_group_reserved', 'Remove a machines reserved by other user from a group');
