INSERT INTO privilege (privilege, descr) values ('machine_powerswitch', 'Start or restart or poweroff machine');
INSERT INTO privilege (privilege, descr) values ('machine_delete', 'Delete machine');
INSERT INTO privilege (privilege, descr) values ('machine_reinstall', 'Reinstall machine');
INSERT INTO privilege (privilege, descr) values ('machine_edit_reserve', 'Reserve machine');
INSERT INTO privilege (privilege, descr) values ('machine_free', 'Free machine');
INSERT INTO privilege (privilege, descr) values ('machine_sed_job', 'Send job to machine');
INSERT INTO privilege (privilege, descr) values ('machine_vnc', 'Open VNC viewer to machine');
INSERT INTO privilege (privilege, descr) values ('machine_terminal', 'Open terminal to machine');
INSERT INTO privilege (privilege, descr) values ('machine_merge', 'Merge machines');
INSERT INTO privilege (privilege, descr) values ('machine_add_to_group', 'Add machine to group');
INSERT INTO privilege (privilege, descr) values ('machine_remove_from_group', 'Remove machine from group');
INSERT INTO privilege (privilege, descr) values ('group_create', 'Create group');
INSERT INTO privilege (privilege, descr) values ('group_edit', 'Edit group');
INSERT INTO privilege (privilege, descr) values ('group_delete', 'Delete group');
INSERT INTO privilege (privilege, descr) values ('group_list_machines', 'List machines in group');
INSERT INTO privilege (privilege, descr) values ('validation_start', 'Start validation test');
INSERT INTO privilege (privilege, descr) values ('autopxe_start', 'Install machine with AutoPXE');
