." Manpage for qa_lib_perl.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_lib_perl man page"
.SH NAME
qa_lib_perl
.SH SYNOPSIS
Various perl libraries used by QA tools.
.SH TYPE
lib
.SH DESCRIPTION
Various QA perl libraries, result parsers, etc.
.SH README
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later.
.SH UPSTREAM
None.
.SH AUTHOR
Vilem Marsik, Lukas Lipavsky <vmarsik@suse.cz, llipavsky@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>, Vilem Marsik <VMarsik@novell.com>
