." Manpage for qa_workplace_desktop-integration.
." Contact Jia Yao <jyao@novell.com> to correct errors or typos.
.TH man 8 "26 Oct 2012" "1.0" "qa_workplace_desktop-integration man page"
.SH NAME
qa_workplace_desktop-integration
.SH SYNOPSIS
None.
.SH TYPE
Tools and helpers for the desktop integration of QA Automation tools
.SH DESCRIPTION
hamsta-cscreen:
.br
  Tools for a web link to open the serial console of a machine in the local
  terminal emulator, The link can look like this:
.br
    hamsta-cscreen:qaserial.qa/ix64ph043
.br
  The qaserial.qa is the console server, the ix64ph043 is the hamsta client
  machine which link the console server with serial cable.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal code. Not to be distributed.
.SH LICENSE
SUSE Proprietary.
.SH UPSTREAM
None.
.SH AUTHOR
Jia Yao <jyao@suse.com>
.SH MAINTAINER
Jia Yao <jyao@suse.com>
