." Manpage for qa_lib_frontenduser.
." Contact Pavel Kacer <pkacer@suse.com> to correct errors or typos.
.TH man 8 "09 Oct 2012" "1.0" "qa_lib_frontenduser man page"
.SH NAME
qa_lib_frontenduser
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
Hamsta and QADB user authentication and management web frontend library. Written in PHP.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, our code.
.SH LICENSE
SUSE Proprietary (although may end up all being GPL v2 or later, depending on outcome of legal review).
.SH UPSTREAM
http://qadb.suse.de/qadb
.SH AUTHOR
Vilem Marsik   <vmarsik@suse.cz>
Pavel Kacer    <pkacer@suse.com>
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
Pavel Kacer <pkacer@suse.com>
