#!/bin/bash

export LANG=C

this="`which "$0"`"
cd "`dirname "$this"`"

[ -r PROJECT/config ] && source PROJECT/config

# Configuration - will be moved to some file later
if [ -r config ] 
then
	source config
else
	source config.example
fi

# start server 

echo Now starting web server...
webfsd -p $PORT -R $REPOSITORY -F -e 0
echo Web server stopped...
