." Manpage for qa_tools.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_tools man page"
.SH NAME
qa_tools
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
Internal package. qa_tools is a set of tools facilitating automated system installations and other related tasks.
This package contains QA automation scripts:
.br
install.pl - reinstalls the system (GRUB systems only)
.br
cmllist.pl - grep in systems on cml.suse.cz
.br
product.pl - guesses the SuSE product and others
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, Our code. Does it make sense to provide this?
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later. Lots of internal code developed.
.SH UPSTREAM
http://weather.ou.edu/~apw/projects/stress/
.SH AUTHOR
Vilem Marsik <vmarsik@suse.cz>, Patrick Kirsch <pkirsch@suse.de>
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
