#! /bin/sh
### BEGIN INIT INFO
# Provides:       hamsta-multicast-forward
# Required-Start: $network $remote_fs
# Required-Stop:  $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description: Hamsta Multicast Forwarder
# Description: Hamsta multicast forward process - takes and forwards UDP multicasts
### END INIT INFO

. /etc/rc.status
rc_reset

PIDFILE='/var/run/hamsta-multicast-forward.pid'

case "$1" in
    start)
        ps aux | grep "SCREEN -S hamsta-multicast-forward" | grep -v grep > /dev/null
        [ $? == 0 ] && exit
        echo -n "Starting Hamsta Multicast Forwarder"
        screen -S hamsta-multicast-forward -l -d -m /bin/bash -c 'cd /usr/share/hamsta/; ./hamsta-multicast-forward.pl'
	rc_status -v
        ;;
    stop)
        echo -n "Shutting down Hamsta Multicast Forwarder"
	killall hamsta-multicast-forward.pl
	rc_status -v
        ;;
    restart|reload)
        $0 stop
	sleep 1
        $0 start
	rc_status
        ;;
    status)
        echo -n "Checking for service Hamsta Multicast Forwarder"
        ps aux | grep hamsta-multicast-forward.pl | grep -v grep > /dev/null
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

