#!/bin/sh
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************

#verify the database status
DB_type=
DB_host=
DB_name=
DB_user=
DB_passwd=

#get the DB information

db_host_name=`grep "PDO_" /srv/www/htdocs/hamsta/config.php |sed '/^\s*#/d'|awk -F'[,) (]' '/DATABASE/{gsub(/\"/,"");print $4}'`
DB_type=${db_host_name%%:*}
DB_host=${db_host_name##*host=}
DB_host=${DB_host%%;*}
DB_name=${db_host_name##*dbname=}
DB_user=`grep "PDO_USER" /srv/www/htdocs/hamsta/config.php |sed '/^\s*#/d'|awk -F'[,) (]' '{gsub(/\"/,"");print $4}'`
DB_passwd=`grep "PDO_PASSWORD" /srv/www/htdocs/hamsta/config.php |sed '/^\s*#/d'|awk -F'[,) (]' '{gsub(/\"/,"");printf $4}'`

if [ "$DB_type" == "mysql" ];then
	if [ "$DB_passwd" == "" ];then
		passwd_arg=""
	else
		passwd_arg="-p$DB_passwd"
	fi 
	mysql -u $DB_user -h $DB_host $passwd_arg -e "use hamsta_db;"
	if [ $? != 0 ];then
	echo "Database error,please check the database config"
	exit 1
	fi
fi

screen -S hamsta-master -l -d -m /bin/bash -c 'cd /usr/share/hamsta/master; ./master.pl'


