." Manpage for qa_conf_unstable.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_conf_unstable man page"
.SH NAME
qa_conf_unstable
.SH SYNOPSIS
None
.SH TYPE
configuration
.SH DESCRIPTION
Installation of this package adds configuration for QA tools, that makes them use development versions of QA Automation server. For development only!.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
None.
.SH LICENSE
None.
.SH UPSTREAM
None.
.SH AUTHOR
Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <llipavsky@suse.cz>
