." Manpage for qa_db_report.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_db_report man page"
.SH NAME
qa_db_report
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
qa_db_report is used to process CTCS2 test results and send them to QADB. Formerly part of qa_tools, this package contains qa_db_report.pl andrelated files. These files now should only be installed on one centralserver that alone does the direct MySQL writing. Clients only sendtest results and basic configuration, code in this package does theactual QADB submit.
.SH README
None. 
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, Our code. Not to be redistributed.
.SH LICENSE
License: n/a. Spec file license: GPL v2 or later.
.SH UPSTREAM
None.
.SH AUTHOR
Vilem Marsik <vmarsik@suse.cz>, Patrick Kirsch <pkirsch@suse.de>, Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>, Vilem Marsik <VMarsik@novell.com>
