#!/bin/bash

# Usage: $0 [test_network_number]

[ -z $1 ] && NETWORK=$1

# otherwise network is unset and will be set in config

./01_check_test_added

./02_build_repo

./03_check_build

if [ $? -ne 0 ]
then
	echo "ERROR: Build of test repository failed." >&1
	exit 1
fi

./04_prepare_virtenv

./05_check_image_build

if [ $? -ne 0 ]
then
	echo "ERROR: Build of kiwi images failed." >&1
	exit 1
fi

./10_run_tests

./98_delete_virtenv

./99_delete_repo

