#!/bin/bash

# Usage: $0 [test_network_number]

NETWORK=1

[ -z $1 ] && NETWORK=$1

REPOROOT=/tmp/repo
REPOPATH=test/network_$NETWORK
PRODUCTS="SLE-11-SP3 SLE-12"
REPOPORT=8888

01_check_test_added

02_build_repo

03_check_build

if [ $? -ne 0 ]
then
	echo "ERROR: Build of test repository failed." >&1
	exit 1
fi


04_prepare_virtenv

10_run_tests

98_delete_virtenv

99_delete_repo

