." Manpage for qa_conf_virtteam.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "09 Nov 2011" "1.0" "qa_conf_virtteam man page"
.SH NAME
qa_conf_virtteam
.SH SYNOPSIS
None
.SH TYPE
configuration
.SH DESCRIPTION
Custom config options for the virtualization team. For test use only!
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
For test use only!
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
None.
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Dan Collingridge <dcollingridge@suse.com>
.SH MAINTAINER
Jason Douglas <jdouglas@suse.com>
