." Manpage for qa_lib_tblib.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_lib_tblib man page"
.SH NAME
qa_lib_tblib
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
TBlib web frontend library. Works with PHP and MySQL. Originally developed for QA database. Set of functions for DB access and generating HTML tags.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal, our code. Distribute only if needed to satisfy dependencies. This library package may have been distributed previously for external projects under a GPLv2 license.
.SH LICENSE
SUSE Proprietary. Contains library files for jquery and gs_sortable. May need to be GPLv2 due to previous potential distribution and outside contributions (see "DISTRIBUTION" section above).
.SH UPSTREAM
http://qadb.suse.de/qadb
.SH AUTHOR
Vilem Marsik   <vmarsik@suse.cz>
.SH MAINTAINER
Vilem Marsik <VMarsik@novell.com>
