.\" Process this file with
.\" groff -man -Tascii reinstall.pl.8
.\"
.TH "reinstall.pl" "8"
.SH NAME
reinstall.pl \- tries to reinstall the current machine using 
.BR grub (8)
,
.B AutoYaST
, and 
.BR setupgrubforinstall (8)

.SH SYNOPSIS
.B reinstall.pl
.I <CML reinstall source>

.SH USEAGE
.B Usage: ./reinstall.pl -p <Install repo> -s [SDK repo] -o [Install option] -u [User profile]

.SH DESCRIPTION
.B reinstall.pl
does following actions:

(1) analyzes the system to find out partitions, IP address, location etc.

(2) creates an AutoYaST reinstall profile and stores it to
.I nfs://10.20.1.229:/srv/hamsta
(it is also accessible as
.I http://bender.suse.cz/hamsta
). 

(3) using
.BR setupgrubforinstall (8)
, sets up the system to boot from the CML source using the prepared profile

(4) reboots, which causes the reinstallation to start.

Every product has different syntax of the AutoYaST config files.
And every product has different bugs.
For this reason, the script has different base AutoYaST script for different products, the functions select different patterns and packages, and so on.
You will probably need to customize this script for newer products.

.SH STATUS
This reinstall script seemed to work for OpenSuSE>=10.3 and SLES>=10.

.SH AUTHOR
Vilem Marsik <vmarsik@novell.com>

.SH "SEE ALSO"
.BR setupgrubforinstall (8)
.BR grub (8)
.BR modify_xml.pl (1)

