#!/bin/bash
# ****************************************************************************
# Copyright (c) 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#

# Install require patterns
patterns="X11 gnome desktop-gnome"
for p in $patterns; do
	result=`zypper --no-refresh search -i -t pattern $p |tail -n 1`;

	if [ "$result" = "No packages found." ]; then
		zypper -n install -t pattern $p;
	else
		echo $result;
	fi
done

# Enable accessibility
status=`gconftool-2  -g /desktop/gnome/interface/accessibility`
if [ "$status" = "false" ]; then
	gconftool-2  -s --type=Boolean /desktop/gnome/interface/accessibility ture;
else
	echo "accessibility is enabled"
fi

# Enable xhost +
xhost_path=~/.config/autostart/xhost.desktop
if [ ! -f $xhost_path ]; then
	echo "Setup: autostart xhost + when gdm restart"
	mkdir -p ~/.config/autostart;
	cat >>$xhost_path <<'EOF'
[Desktop Entry]
Type=Application
Exec=xhost +
Hidden=false
X-Gnome-Autostart-enabled=true
Name=xhost
Comment=xhost + to allow hamsta run UI tests
EOF
	autoxhost=true
fi

# Make root user auto login X window
sut_user=`who |grep :0 | head -n 1 |awk {'print $1'}`
gdm_conf_path="/etc/gdm/custom.conf"
gdm_status=`grep -c "\[daemon\]" $gdm_conf_path`

if [ $gdm_status = "0" ] && [ $sut_user = "root" ] ; then
	echo "Setup: root user auto login X window when gdm restart"
	cat >>$gdm_conf_path <<'EOF'

[daemon]
TimedLoginEnable=true
AutomaticLoginEnable=true
TimedLogin=root
AutomaticLogin=root
TimeLoginDelay=5
EOF
	autologin=true;
fi

# Restart gnome session
if [ $autoxhost ] || [ $autologin ]; then
	echo "Restart gnome session";
	sudo /usr/sbin/rcxdm restart;
else
	echo "Done!";
	exit 0;
fi


