#!/bin/bash
# ****************************************************************************
# Copyright (c) 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


curl=curl

printhelp()
{
	cmd=`basename $0`
	echo -e "Usage:\t$cmd <CML source> <autoyast XML>"
	echo -e "  or :\t$cmd <CML source> [<cmdline arguments...>]"
	echo
	echo -e "Example:\t$cmd ftp://cml.suse.cz/netboot/find/openSUSE-11.0-RC3-DVD-ppc64 http://bender.suse.cz/autoinst/autoinst_vulture.xml"
	echo -e "\t(yet you perhaps would like to use IP addresses instead of hostnames...)"
	echo
	exit 1
}

if [ "$#" -lt 1 -o "$1" == "--help" ]
then
	printhelp
fi

insturl=$1
shift
arch=`uname -m`

curlprobe()
{
	local url="$1"
	$curl -o /dev/null -I -L -f -s "$url" || return 1
}

if [ $# -lt 2 ]
then
	hostip=`ifconfig eth0 | perl -ne 'print $1 if $_=~/addr:((\d{1,3}\.){3}\d{1,3})/'`
	if [ $# -eq 1 ]
	then
		ay_xml=$1
		shift
		params="vga=normal autoyast=$ay_xml netdevice=eth0 netwait=10 $hostip install=$insturl"
	else
		params="vga=normal netdevice=eth0 netwait=10 $hostip install=$insturl"
	fi
else
	params="$@"
fi

###add vnc and ssh tag to kernel parameter #######
#params="$params $ssh_enable $vnc_enable"
bootloaderconf=/etc/lilo.conf
imagedir='/boot/loader'
TMPFILE=`mktemp -q /tmp/distinst.XXXXXX`
if [ $? -ne 0 ]
then
	echo "$0: Cannot create temp file, exiting."
	exit 1
fi
imagedir=`mktemp -d -q $imagedir-XXXXXX`
if [ $? -ne 0 ]
then
	echo "$0: Cannot create temp directory, exiting"
	exit 1
fi
mkdir -p "$imagedir"

cleanup()
{
	[ -f $TMPFILE ] && rm $TMPFILE
}
trap cleanup EXIT

kernelurl="$insturl/suseboot/inst64"
initrdurl="$insturl/suseboot/initrd64"

# This is to support the case that PPC might not have an initrd in the repo
skipInitrd="yes"

$curl -f -L -o "$imagedir"/inst64 "$kernelurl"
$curl -L -o "$imagedir"/initrd64 "$initrdurl"

# Since the install kernel is required, it's a failure if it isn't there
if [ ! -e "$imagedir"/inst64 ]
then
	echo "Could not download image(inst64) from '$insturl' to '$imagedir'"
	exit 1
fi

# But since the initrd is optional, it can be skipped if it isn't there
if [ -e "$imagedir"/initrd64 ]
then
	skipInitrd="no"
fi

# IMPORTANT:
# This is workaround for bnc#809148
# It was not tested with SLES10-SP4 potential issue with SLE10 codeline
# Tested with SLES11-SP[23]
# it makes initrd is NEVER used even when it is present in the repo
skipInitrd="yes"


title="Installation"
count=`grep -c "label = Installation" $bootloaderconf`
if [ $count -gt 0 ]
then
    title="${title}$((count+1))"
fi

echo "" >> $bootloaderconf
echo "image = $imagedir/inst64" >> $bootloaderconf
echo "    label = $title" >> $bootloaderconf
echo "    optional" >>$bootloaderconf
echo "    append = \"$params\"" >> $bootloaderconf
if [ "$skipInitrd" == "no" ]
then
	echo "    initrd = $imagedir/initrd64" >> $bootloaderconf
fi
cat $bootloaderconf | grep root -m 1 >> $bootloaderconf
sync

# start the installation with reboot
sed "s/^default.*$/default = $title/" $bootloaderconf > $TMPFILE
cp -v $TMPFILE $bootloaderconf	# workaround, instead of using perl
echo "edited bootloader config"
lilo

echo "done."


