." Manpage for qadb.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qadb man page"
.SH NAME
qadb
.SH SYNOPSIS
None.
.SH TYPE
tool
.SH DESCRIPTION
For many years, QADB (the “QA Database”) has served as the primary test results repository for automated testing within SUSE. All automated test results and logs can be sent to and stored by QADB for later retrieval and comparison. QADB supports both functional (pass/fail) and performance/benchmark (quantitative) test results. Regression analysis can be performed on both types of results, with performance results being shown in tabular and graphical format for easier consumption.
.br
The QADB user interface was developed using PHP and JavaScript and uses a MySQL database capable of storing and quickly retrieving millions of automated test results. QADB is packaged in an RPM for easy installation and updating.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
Internal code. Not to be redistributed.
.SH LICENSE
SUSE Proprietary. However it includes/sources in various libraries including PHPlot and Epoch (which are physically located in the package) and jquery and gs_sortable (which are sourced in from TBLIB). PHP and CSS code are also sourced in through TBLIB.
.SH UPSTREAM
None.
.SH AUTHOR
Patrick Kirsch <pkirsch@suse.de>, Vilem Marsik <vmarsik@suse.cz>
.SH MAINTAINER
None.
