.\" Process this file with
.\" groff -man -Tascii mysql_loc.rc.5
.\"
.TH ".mysql_loc.rc" "QADB" "5"
.SH NAME
~/.mysql_loc.rc \- specifies location of QADB instance

.SH EXAMPLE
.RS
.nf
sql_host=qadb.suse.de
sql_db=qadb
sql_user=hamsta-default
sql_pwd=
.fi
.RE

.SH DESCRIPTION

.IP "\fBsql_host"
hostname of the computer with MySQL server

.IP "\fBsql_db"
MySQL database name

.IP "\fBsql_user
MySQL login

.IP "\fBsql_pwd"
MySQL password

.SH "SEE ALSO"
.BR qa_db_report.pl (1),
.BR select_db.pl (1)
