#!/usr/bin/python

from robot.libraries.BuiltIn import BuiltIn

class BuildLogChecker:
    """ Reads the build log (generated by build-repo command, compares it to
    list of known broken packages and preformat the results to easy to eat 
    way for robot framework.
    """
    
    def __init__(self, broken):
        """ Read and parse buildlog and broken package list
        """
        self._broken = {}
        with open(broken, 'r') as br:
            for line in br:
		line = line.strip()
		if len(line) > 0 and not line.startswith('#'):
                    (pack, products) = line.split(':')
                    self._broken[pack] = products.split(' ')

    def check_package_build_status(self, pack, product, status):
        listed = pack in self._broken and (product in self._broken[pack] or '*' in self._broken[pack])
        if status == 'fail' and not listed:
           raise AssertionError("Package " + pack + " on " + product + " build failed with result " + status)
        elif status != 'fail' and listed:
           # status can be 'ok' or 'skip'
           BuiltIn().set_tags('build_fixed');
           raise AssertionError("Package " + pack + " on " + product + " build suceeded, but it was unexpected.")

