." Manpage for qa_lib_strongwind
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_lib_strongwind man page"
.SH NAME
qa_lib_strongwind
.SH SYNOPSIS
None.
.SH TYPE
test tool (framework)
.SH DESCRIPTION
qa_lib_strongwind is a test lib for writing test cases for desktop apps.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None
.SH WARNINGS
Don't press Ctrl-C while testing run.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, no patches. This ships as part of openSUSE, but we have made some changes.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://git.gnome.org/browse/strongwind
.SH AUTHOR
Leon Wang <llwang@novell.com>
.SH MAINTAINER
Leon Wang <llwang@novell.com>
