." Manpage for qa_lib_openid.
." Contact David Mulder <dmulder@suse.com> to correct errors or typos.
.TH man 8 "23 May 2012" "1.0" "qa_lib_openid man page"
.SH NAME
qa_lib_openid
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
Extending the art & spirit of PHP, Zend Framework is based on simplicity,
object-oriented best practices, corporate friendly licensing, and a rigorously
tested agile codebase. Zend Framework is focused on building more secure,
reliable, and modern Web 2.0 applications & web services, and consuming widely
available APIs from leading vendors like Google, Amazon, Yahoo!, Flickr, as
well as API providers and catalogers like StrikeIron and ProgrammableWeb.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
Adds the openid consumer components of the Zend framework to the php include path of the installing server.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
BSD
.SH UPSTREAM
http://framework.zend.com/
.SH AUTHOR
Zend Community
.SH MAINTAINER
David Mulder <dmulder@suse.com>
