." Manpage for qa_sdk_tcf_generator.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_sdk_tcf_generator man page"
.SH NAME
qa_sdk_tcf_generator
.SH SYNOPSIS
qa_sdk_tcf_generator dir/tar [option]
.SH TYPE
test tools
.SH DESCRIPTION
Generate a sample of a tcf file from the program directory.
.br
The generator is looking for a directory or tgz file, find out the executable script, and then create a tcf format file.
.SH README
None.
.SH OPTIONS
-t timeout
.br
-n times to run
.br
-f run the test script in front ground
.br
-b run the test script in background
.br
-r a regex of executable script name
.SH WHAT IT DOES
A new tcf file will be generated in the current directory.
.SH COMMON PROBLEMS
The script will only find executable file end with .sh/.pl/.py
.br
The local directory should be "qapackage" under svn directory.
.br
Make sure the test script name is ended with .sh or .pl or .py.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
Jerry Tang  <jtang@novell.com>
.SH MAINTAINER
Jerry Tang <jtang@novell.com>
