." Manpage for qa_ajaxterm.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_ajaxterm man page"
.SH NAME
qa_ajaxterm
.SH SYNOPSIS
None.
.SH TYPE
test tool
.SH DESCRIPTION
qa_ajaxterm is a tool to enable ssh connect from hamsta front-end to SUT.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 2 patches. Component of hamsta, thus no need to distribute.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
http://antony.lesuisse.org/software/ajaxterm/
.SH AUTHOR
Leon Wang <llwang@novell.com>
.SH MAINTAINER
Leon Wang <llwang@novell.com>
