." Manpage for qa_setvncserver.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_setvncserver man page"
.SH NAME
qa_setvncserver
.SH SYNOPSIS
None.
.SH TYPE
test tool
.SH DESCRIPTION
qa_setvncserver is a tool to set vncserver on SUT.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. Internal tool. Not to be redistributed.
.SH LICENSE
GPL v2 or later
.SH UPSTREAM
None.
.SH AUTHOR
Leon Wang <llwang@novell.com>
.SH MAINTAINER
Leon Wang <llwang@novell.com>
