." Manpage for qa_cscreen.
." Contact Jia Yao <jyao@novell.com> to correct errors or typos.
.TH man 8 "26 Oct 2012" "1.0" "qa_cscreen man page"
.SH NAME
qa_cscreen
.SH SYNOPSIS
None.
.SH TYPE
test tool
.SH DESCRIPTION
qa_cscreen is a tool to enable ssh connect console server from hamsta front-end to SUT by serial tty.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
External, 2 patches. Component of hamsta, thus no need to distribute.
.SH LICENSE
GPL v2 or later; LGPL v2.1
.SH UPSTREAM
http://antony.lesuisse.org/software/ajaxterm/
.SH AUTHOR
Jia Yao <jyao@suse.com>
.SH MAINTAINER
Jia Yao <jyao@suse.com>
