." Manpage for qa_lib_keys.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "21 Oct 2011" "1.0" "qa_lib_keys man page"
.SH NAME
qa_lib_keys
.SH SYNOPSIS
None
.SH TYPE
tool
.SH DESCRIPTION
Contains ssh keys so that SUTs can ssh to each other.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
Changes ssh fingerprint. Give anyone root access to the host. Install on SUT only!
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH DISTRIBUTION
Internal, Our code. ABSOLUTELY not to be redistributed (ssh keys:).
.SH LICENSE
SUSE Proprietary
.SH UPSTREAM
None.
.SH AUTHOR
Vilem Marsik <vmarsik@suse.cz>
.SH MAINTAINER
Lukas Lipavsky <LLipavsky@novell.com>
