#!/bin/bash
# ****************************************************************************
# Copyright © 2011 Unpublished Work of SUSE. All Rights Reserved.
# 
# THIS IS AN UNPUBLISHED WORK OF SUSE.  IT CONTAINS SUSE'S
# CONFIDENTIAL, PROPRIETARY, AND TRADE SECRET INFORMATION.  SUSE
# RESTRICTS THIS WORK TO SUSE EMPLOYEES WHO NEED THE WORK TO PERFORM
# THEIR ASSIGNMENTS AND TO THIRD PARTIES AUTHORIZED BY SUSE IN WRITING.
# THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
# TREATIES. IT MAY NOT BE USED, COPIED, DISTRIBUTED, DISCLOSED, ADAPTED,
# PERFORMED, DISPLAYED, COLLECTED, COMPILED, OR LINKED WITHOUT SUSE'S
# PRIOR WRITTEN CONSENT. USE OR EXPLOITATION OF THIS WORK WITHOUT
# AUTHORIZATION COULD SUBJECT THE PERPETRATOR TO CRIMINAL AND  CIVIL
# LIABILITY.
# 
# SUSE PROVIDES THE WORK 'AS IS,' WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING WITHOUT THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. SUSE, THE
# AUTHORS OF THE WORK, AND THE OWNERS OF COPYRIGHT IN THE WORK ARE NOT
# LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION
# WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK.
# ****************************************************************************
#


SUBMODULE=""
PART="$1"
[ -z "$PART" ] || SUBMODULE="${PART}_"

# needed if we re-source this file - cleanup before reading it again
if [ ! -z "$full_qa_config" ] ; then
	for var in `echo "$full_qa_config" | sed 's/=.*//'` ; do
		unset $var
	done
fi

# read all configs in correct order
set > /tmp/$$.before # read all variables before we processed qa config
for file in /etc/qa/*
do
	if [ -f "$file" -a -r "$file" ]
	then
		# do not source rpmsave files
		echo "$file" | grep -q '\.rpmsave$' || source "$file"
	fi
done
unset file

[ -r ~/.qarc ] && source ~/.qarc

set > /tmp/$$.after # read all variables after we processed qa config

full_qa_config=`diff /tmp/$$.before /tmp/$$.after | grep "^>" | sed 's/^> //' | grep -v "^_=\|PIPESTATUS"`

rm /tmp/$$.after /tmp/$$.before

#
# Helper functions
#

# Dump all config
function dump_qa_config
{
	echo "$full_qa_config" | grep "^$SUBMODULE" | sed s/^$SUBMODULE// | sed "s/='\(.*\)'$/=\1/"
}

# Get one specific config value
function get_qa_config
{
	# This needs the variable to be exported (which is done by var function)
	eval echo \$$SUBMODULE$1 
}


