." Manpage for qa_lib_virtauto-data.
." Contact David Mulder <dmulder@novell.com> to correct errors or typos.
.TH man 8 "11 Jul 2011" "1.0" "qa_lib_virtauto-data man page"
.SH NAME
qa_lib_virtauto-data
.SH SYNOPSIS
None.
.SH TYPE
None.
.SH DESCRIPTION
Data for virtualization automation library.
.SH README
None.
.SH OPTIONS
None.
.SH WHAT IT DOES
None.
.SH COMMON PROBLEMS
None.
.SH WARNINGS
None.
.SH SEE ALSO
None.
.SH BUGS
None.
.SH DISTRIBUTION
None.
.SH LICENSE
None.
.SH UPSTREAM
None.
.SH AUTHOR
Dan Collingridge <dcollingridge@novell.com>, Lukas Lipavsky <llipavsky@suse.cz>
.SH MAINTAINER
None.
