#!/bin/bash

source /etc/qavirttest/utils.config

CONFIG="/tmp/autotest.conf.$NETWORK"
BUILDLOG="/$REPOROOT/$REPOPATH/autotest.buildlog"

# Create configuration for building
cat > $CONFIG << EOF
REPO="$REPOROOT/$REPOPATH"
PRODUCTS="$PRODUCTS"
ARCHS="`arch`"
PORT=$REPOPORT
BUILDLOG="$BUILDLOG"
EOF

MY_DIR=`dirname "$0"`

cd "$MY_DIR"

../../build-repository $CONFIG



# remove temp. config
rm $CONFIG
